### ISSUE TITLE
rules_dic.json preguntas.

### ISSUE THREAD

**Issue by fjl2020** [jjeg1979/DMRI_MT4#1]
En el archivo rules_dic.json me daba error y le quite la ultima coma del diccionario y me funcionó, por otro lado en el diccionario el SAr parabolico está definido como SAR(.... , esta correctamente definido  o debería decir iSAR(....?

**Comment by jjeg1979** [comment]
Efectivamente Fernando, es así. De nuevo, el tener tantos directorios me jugó una mala pasada. En el que tengo yo en el desarrollo (que aún no he "pusheado" están esos temas solucionados. Lo voy a subir corregido y deberiaís de poder tenerlo bien.
