### ISSUE TITLE
Header y value con distintos nombres.

### ISSUE THREAD

**Issue by fjl2020** [jjeg1979/DMRI_MT4#5]
Los headers en el archivo z_VAC_header_CBBRDown por ejemplo( C_BBR_Down_50_3) no coinciden con el archivo z_VAC_values_CBBRDown de la función (C_BBR_Dwn_50_3) si bien el extractor funcionan cuando uno quiere obtener el diccionario para continuar con el proceso de cara al Tradingbuyrules se complica.

**Comment by jjeg1979** [comment]
Gracias por el comentario, lo he corregido y he verificado que en diccionario estuviese correcto
