### ISSUE TITLE
Issue en archivo main.py para trabajar con reglas bajistas

### ISSUE THREAD

**Issue by fjl2020** [jjeg1979/DMRI_MT4#9]
En el archivo main.py en la linea 120 dice : 
dict_rules, "payload/reglas_extraidas_UP.txt"
y se debería cambiar a : 
dict_rules, f"payload/reglas_extraidas_{DIRECTION}.txt"
para que funcione con down y up

**Comment by jjeg1979** [comment]
Solucionado con el último push realizado. He refactorizado parte del código. Sigo refactorizando.
